/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Config */
        get: operations["default_config_api_config_default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transactions
         * @description The raw rows the pipeline reads, newest first, for the records page. Nothing is reshaped:
         *     this is what Rho's /transactions returns, so amounts stay signed minor units. `beat` limits
         *     the result to the rows one demo beat added (history, inject-1, inject-2).
         */
        get: operations["transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accounts
         * @description Balance snapshot for the stage, in Rho's /accounts shape.
         */
        get: operations["accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/narrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Narrate */
        post: operations["narrate_api_narrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description A clarifying question under one finding, answered from that finding's evidence pack.
         */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountsResponse */
        AccountsResponse: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "history" | "inject-1" | "inject-2";
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Accounts
             * @description Rho /accounts shape: id, name, account_type, balance{amount, currency}
             */
            accounts: {
                [key: string]: unknown;
            }[];
        };
        /** AlertText */
        AlertText: {
            /** Finding Id */
            finding_id: string;
            /** Headline */
            headline: string;
            /** What Moved */
            what_moved: string;
            /** Why */
            why: string;
        };
        /**
         * AskRequest
         * @description A clarifying question in the thread under one alert or report item. The answer is
         *     grounded in an evidence pack built server-side for that finding: its facts, the vendor's
         *     monthly series, and the individual charges in the evaluated and prior month.
         */
        AskRequest: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "history" | "inject-1" | "inject-2";
            /** Finding Id */
            finding_id: string;
            /** Question */
            question: string;
            /**
             * Thread
             * @description Earlier turns in this thread, oldest first
             * @default []
             */
            thread: components["schemas"]["AskTurn"][];
            config?: components["schemas"]["Config"] | null;
            /**
             * Overrides
             * @default []
             */
            overrides: components["schemas"]["Override"][];
            /**
             * Open Issues
             * @default []
             */
            open_issues: components["schemas"]["OpenIssue"][];
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /**
             * Source
             * @enum {string}
             */
            source: "claude" | "template";
            /**
             * Evidence Used
             * @description Which parts of the evidence pack were available
             * @default []
             */
            evidence_used: string[];
        };
        /** AskTurn */
        AskTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "bot";
            /** Text */
            text: string;
        };
        /** Baseline */
        Baseline: {
            /** N Obs */
            n_obs: number;
            /** Expected Monthly */
            expected_monthly: number;
            /**
             * Growth Pct
             * @description Fitted month-over-month growth, usage vendors
             */
            growth_pct?: number | null;
            /**
             * Sigma
             * @description Std dev of the vendor's own residuals
             */
            sigma?: number | null;
            /** Last Price */
            last_price?: number | null;
            /** Cost Per Head */
            cost_per_head?: number | null;
            /**
             * Headcount Proxy
             * @description Cardholder proxy used for the evaluated month
             */
            headcount_proxy?: number | null;
        };
        /**
         * CashPosition
         * @description What the bank can say without asking: runway from total cash and net burn, and what the
         *     operating balance allows. All arithmetic, assumptions stated. Inflows are cash receipts, not
         *     revenue: a large unclassified one is asked about (`inflow_ask`), and the answer changes net burn.
         */
        CashPosition: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Operating Balance */
            operating_balance: number;
            /** Treasury Balance */
            treasury_balance: number;
            /** Total Cash */
            total_cash: number;
            /**
             * Monthly Inflows
             * @description Average settled inflows over the 3 complete months before the evaluated month
             */
            monthly_inflows: number;
            /**
             * Net Burn Monthly
             * @description Trailing monthly spend minus monthly inflows, floored at 0
             */
            net_burn_monthly: number;
            /** Runway Months */
            runway_months: number | null;
            /** Operating Months Of Burn */
            operating_months_of_burn: number | null;
            /** Buffer Months */
            buffer_months: number;
            /**
             * Recommended Operating
             * @description buffer_months × net burn
             */
            recommended_operating: number;
            /**
             * Sweep To Treasury
             * @description Operating balance above the buffer, 0 if none
             */
            sweep_to_treasury: number;
            /**
             * Shortfall From Treasury
             * @description Top-up needed to reach the buffer, 0 if none
             */
            shortfall_from_treasury: number;
            /** Treasury Apy */
            treasury_apy: number;
            /**
             * Treasury Upside Monthly
             * @description sweep × APY / 12
             */
            treasury_upside_monthly: number;
            /**
             * Inflows
             * @description Settled inflows in the averaging window
             * @default []
             */
            inflows: components["schemas"]["InflowItem"][];
            /**
             * Inflow Ask
             * @description Unclassified inflows large enough to ask about
             * @default []
             */
            inflow_ask: components["schemas"]["InflowItem"][];
        };
        /** Config */
        Config: {
            /** Thresholds */
            thresholds: {
                [key: string]: components["schemas"]["TypeThreshold"];
            };
            /**
             * Report Floor Pct
             * @description Below this share of trailing monthly spend a change is dropped from the report, unless it is a price change, per-head rise or renewal on a vendor whose cost type is confirmed or classified
             * @default 0.0025
             */
            report_floor_pct: number;
            /**
             * Buffer Months
             * @description Months of net burn to keep in operating checking
             * @default 3
             */
            buffer_months: number;
            /**
             * Treasury Apy
             * @description Assumed Rho Treasury yield, for the cash position
             * @default 0.038
             */
            treasury_apy: number;
        };
        /** DriverShare */
        DriverShare: {
            /**
             * Driver
             * @enum {string}
             */
            driver: "price" | "volume" | "new" | "missing" | "who";
            /** Share */
            share: number;
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Vendor */
            vendor: string;
            /** Category */
            category: string;
            /**
             * Cost Type
             * @enum {string}
             */
            cost_type: "usage" | "fixed" | "headcount" | "annual" | "payroll";
            /**
             * Cost Type Source
             * @enum {string}
             */
            cost_type_source: "taxonomy" | "llm" | "user" | "default";
            /**
             * Kind
             * @enum {string}
             */
            kind: "growth_break" | "price_change" | "new_vendor" | "stopped" | "per_head" | "renewal" | "spike";
            /**
             * Route
             * @enum {string}
             */
            route: "alert" | "report" | "ignore";
            /** Actual Monthly */
            actual_monthly: number;
            /**
             * Impact Monthly
             * @description actual - expected; negative for decreases
             */
            impact_monthly: number;
            /** Impact Pct Of Spend */
            impact_pct_of_spend: number;
            baseline: components["schemas"]["Baseline"];
            /** Drivers */
            drivers: components["schemas"]["DriverShare"][];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Ask Cost Type
             * @description Ask the user to confirm cost_type before showing
             * @default false
             */
            ask_cost_type: boolean;
            /**
             * Escalation Of
             * @description OpenIssue id this re-alert escalates
             */
            escalation_of?: string | null;
            /**
             * Cardholders
             * @default []
             */
            cardholders: string[];
            /**
             * Month
             * @description Evaluated calendar month, YYYY-MM
             */
            month?: string | null;
            /**
             * Runway Weeks Delta
             * @description Weeks of runway lost (positive) or gained (negative) if this monthly change persists; None without a cash position or for one-offs
             */
            runway_weeks_delta?: number | null;
        };
        /** Findings */
        Findings: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "history" | "inject-1" | "inject-2";
            /**
             * Window Start
             * Format: date
             * @description Start of the baseline (fitting) window, not the reporting period
             */
            window_start: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            period?: components["schemas"]["Period"] | null;
            cash?: components["schemas"]["CashPosition"] | null;
            /**
             * Transaction Count
             * @description Settled spend rows read, through window_end
             */
            transaction_count?: number | null;
            /**
             * Recurring Vendor Count
             * @description Recurring vendors whose spend reached the report floor in some month (the ones the reports talk about)
             */
            recurring_vendor_count?: number | null;
            /**
             * Data Start
             * @description Earliest transaction date in the data
             */
            data_start?: string | null;
            /** Trailing Monthly Spend */
            trailing_monthly_spend: number;
            /**
             * Last Monthly Spend
             * @description Total spend in the last full month
             */
            last_monthly_spend?: number | null;
            /**
             * Prior Monthly Spend
             * @description Total spend in the month before the last full month, for the report intro
             */
            prior_monthly_spend?: number | null;
            /**
             * Headcount Proxy
             * @description Distinct cardholders in the window
             */
            headcount_proxy: number;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Vendors */
            vendors: components["schemas"]["VendorSummary"][];
            /** Category Totals */
            category_totals: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InflowItem */
        InflowItem: {
            /** Id */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /** Counterparty */
            counterparty: string;
            /**
             * Kind
             * @default unclassified
             */
            kind: ("customer" | "funding" | "refund" | "transfer" | "other") | "unclassified";
            /**
             * Counted
             * @description Counted as cash in (customer or unclassified); funding, refunds and transfers are not
             */
            counted: boolean;
        };
        /**
         * InflowOverride
         * @description The founder's answer to "what was this inflow?". Only customer payments count as cash in.
         */
        InflowOverride: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "customer" | "funding" | "refund" | "transfer" | "other";
        };
        /** NarrateRequest */
        NarrateRequest: {
            findings: components["schemas"]["Findings"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "alerts" | "report";
            /**
             * Open Issues
             * @description Issues already alerted on; their vendors go under 'Needs attention' in reports
             * @default []
             */
            open_issues: components["schemas"]["OpenIssue"][];
        };
        /** NarrateResponse */
        NarrateResponse: {
            /**
             * Alerts
             * @default []
             */
            alerts: components["schemas"]["AlertText"][];
            report?: components["schemas"]["ReportText"] | null;
        };
        /**
         * OpenIssue
         * @description An issue already alerted on; carried by the client so reruns dedupe against it.
         */
        OpenIssue: {
            /** Id */
            id: string;
            /** Vendor */
            vendor: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "growth_break" | "price_change" | "new_vendor" | "stopped" | "per_head" | "renewal" | "spike";
            /** Impact Monthly */
            impact_monthly: number;
        };
        /** Override */
        Override: {
            /** Vendor */
            vendor: string;
            /**
             * Cost Type
             * @enum {string}
             */
            cost_type: "usage" | "fixed" | "headcount" | "annual" | "payroll";
        };
        /**
         * Period
         * @description What a report is about. `first_run` spans all the history read on the first run; `month`
         *     is the calendar month that closed (or is in progress). Distinct from the baseline window,
         *     which is the fitting range and lives in `Findings.window_start/end`.
         */
        Period: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "first_run" | "month";
            /**
             * Label
             * @description "Sep 2025 – Aug 2026" or "September 2026"
             */
            label: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** ReportItemText */
        ReportItemText: {
            /** Finding Id */
            finding_id: string;
            /** Text */
            text: string;
        };
        /** ReportText */
        ReportText: {
            /** Intro */
            intro: string;
            /** Needs Attention */
            needs_attention: components["schemas"]["ReportItemText"][];
            /**
             * Worth Knowing
             * @description Grouped by category
             */
            worth_knowing: {
                [key: string]: components["schemas"]["ReportItemText"][];
            };
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "history" | "inject-1" | "inject-2";
            config?: components["schemas"]["Config"] | null;
            /**
             * Overrides
             * @default []
             */
            overrides: components["schemas"]["Override"][];
            /**
             * Open Issues
             * @default []
             */
            open_issues: components["schemas"]["OpenIssue"][];
            /**
             * Inflow Overrides
             * @default []
             */
            inflow_overrides: components["schemas"]["InflowOverride"][];
        };
        /**
         * TransactionsResponse
         * @description Raw Rho-shaped rows for the records page, untouched (amounts stay signed minor units).
         */
        TransactionsResponse: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "history" | "inject-1" | "inject-2";
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Total
             * @description Rows in the stage before filtering
             */
            total: number;
            /**
             * Matched
             * @description Rows matching the filters
             */
            matched: number;
            /**
             * By Beat
             * @description Rows each demo beat added: history, inject-1, inject-2
             */
            by_beat: {
                [key: string]: number;
            };
            /**
             * Transactions
             * @description Raw rows plus a `_beat` key naming the file that added each
             */
            transactions: {
                [key: string]: unknown;
            }[];
        };
        /** TypeThreshold */
        TypeThreshold: {
            /**
             * Alert Pct
             * @description Alert when monthly impact >= this share of trailing monthly spend
             */
            alert_pct: number;
            /**
             * Alerts
             * @description False for types that never alert (annual, payroll)
             * @default true
             */
            alerts: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VendorSummary */
        VendorSummary: {
            /** Vendor */
            vendor: string;
            /** Category */
            category: string;
            /**
             * Cost Type
             * @enum {string}
             */
            cost_type: "usage" | "fixed" | "headcount" | "annual" | "payroll";
            /**
             * Cost Type Source
             * @enum {string}
             */
            cost_type_source: "taxonomy" | "llm" | "user" | "default";
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "semi-monthly" | "monthly" | "annual" | "irregular";
            /** Monthly Spend */
            monthly_spend: number;
            /** Growth Pct */
            growth_pct?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    default_config_api_config_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    transactions_api_transactions_get: {
        parameters: {
            query?: {
                stage?: "history" | "inject-1" | "inject-2";
                q?: string;
                type?: string;
                account?: string;
                beat?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_api_accounts_get: {
        parameters: {
            query?: {
                stage?: "history" | "inject-1" | "inject-2";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Findings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narrate_api_narrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
